#include "../stdafx.h"

cfg_uint cfg_window_x(GUID(FOO_UI_CHROMIUM_GUID_PREFERENCE_PRIVATE_WINDOW_X), 100);
cfg_uint cfg_window_y(GUID(FOO_UI_CHROMIUM_GUID_PREFERENCE_PRIVATE_WINDOW_Y), 100);
cfg_uint cfg_window_width(GUID(FOO_UI_CHROMIUM_GUID_PREFERENCE_PRIVATE_WINDOW_WIDTH), 800);
cfg_uint cfg_window_height(GUID(FOO_UI_CHROMIUM_GUID_PREFERENCE_PRIVATE_WINDOW_HEIGHT), 494);
cfg_bool cfg_window_is_max(GUID(FOO_UI_CHROMIUM_GUID_PREFERENCE_PRIVATE_WINDOW_MAX), false);